Repository feed-the-people/Front-End, pull requests merged in 2021-01, with the labels that each got.

#14 Basic file structure
  .eslintcache
  .travis.yml
  src/APICalls.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/MainPage/MainPage.css
  src/components/MainPage/MainPage.js
  src/components/MainPage/MainPage.test.js
  src/components/RecipeCard/RecipeCard.js
  src/components/RecipeCard/RecipeCard.test.js
  src/components/RecipePage/RecipePage.css
  src/components/RecipePage/RecipePage.js
  src/components/RecipePage/RecipePage.test.js
  src/components/SignIn/SignInPage.js
  src/components/SignIn/SignInPage.test.js
  src/components/SignUp/SignUpPage.js
  src/components/SignUp/SignUpPage.test.js
  src/components/StyledComponents.js
  src/index.js
  yarn.lock
Labels: MVP ✅, documentation 📓, enhancement ✨, priority 1 🚨, setup 🛠

#22 Sign In and Up
  .eslintcache
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/MainPage/MainPage.js
  src/components/MainPage/MainPage.test.js
  src/components/Profile/Profile.js
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.js
  src/components/SignIn/SignInPage.css
  src/components/SignIn/SignInPage.js
  src/components/SignIn/SignInPage.test.js
  src/components/SignUp/SignUpPage.css
  src/components/SignUp/SignUpPage.js
  src/components/SignUp/SignUpPage.test.js
Labels: MVP ✅, priority 1 🚨

#28 Recipe Card Base
  src/components/RecipeCard/RecipeCard.css
  src/components/RecipeCard/RecipeCard.js
  src/components/RecipeCard/RecipeCard.test.js
Labels: enhancement ✨, setup 🛠, ui/ux 🎨

#33 Formatting
  src/components/CallToAction/CallToAction.css
  src/components/CallToAction/CallToAction.js
  src/components/MainPage/MainPage.js
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.js
  src/components/RecipeBook/RecipeBook.css
  src/components/RecipeBook/RecipeBook.js
  src/components/RecipeCard/RecipeCard.css
  src/components/RecipeCard/RecipeCard.js
Labels: MVP ✅, priority 1 🚨

#48 Connect global recipes
  src/APICalls.js
  src/components/App/App.js
  src/components/MainPage/MainPage.js
Labels: MVP ✅, priority 1 🚨

#61 User login
  src/APICalls.js
  src/components/App/App.js
  src/components/ProfilePage/ProfilePage.js
  src/components/SignIn/SignInPage.js
Labels: MVP ✅, priority 1 🚨

#71 Fix Create Recipe API Call
  src/APICalls.js
  src/components/App/App.js
Labels: bug fix 🐛

#72 User sign up
  src/APICalls.js
  src/components/SignUp/SignUpPage.css
  src/components/SignUp/SignUpPage.js
Labels: MVP ✅, priority 1 🚨

#76 Testing ; Recipe Related Components
  .eslintcache
  src/components/CallToAction/CallToAction.js
  src/components/RecipeBook/RecipeBook.js
  src/components/RecipeBook/RecipeBook.test.js
  src/components/RecipeCard/RecipeCard.js
  src/components/RecipeCard/RecipeCard.test.js
  src/components/RecipeForm/RecipeForm.js
  src/components/RecipeForm/RecipeForm.test.js
Labels: documentation 📓, testing ⚙️

#79 User recipe book
  src/APICalls.js
  src/components/RecipeBook/RecipeBook.css
  src/components/RecipeBook/RecipeBook.js
Labels: MVP ✅, priority 1 🚨

#84 Disable Sign Up Button
  src/components/SignUp/SignUpPage.js
Labels: enhancement ✨

#77 Upload recipe
  .eslintcache
  package-lock.json
  package.json
  src/APICalls.js
  src/components/Profile/Profile.js
  src/components/ProfilePage/ProfilePage.js
  src/components/RecipeBook/RecipeBook.js
  src/components/RecipeBook/RecipeBook.test.js
  src/components/RecipeForm/RecipeForm.css
  src/components/RecipeForm/RecipeForm.js
  src/components/RecipeForm/RecipeForm.test.js
  src/setupTests.js
Labels: MVP ✅, priority 1 🚨

#85 A user can't submit a recipe until all form fields are filled
  .eslintcache
  src/components/RecipeForm/RecipeForm.js
Labels: enhancement ✨

#87 Dynamic recipe page
  src/APICalls.js
  src/components/App/App.js
  src/components/MainPage/MainPage.js
  src/components/RecipeBook/RecipeBook.js
  src/components/RecipeCard/RecipeCard.js
  src/components/RecipePage/RecipePage.js
  src/components/RecipePage/RecipePage.test.js
Labels: MVP ✅, priority 1 🚨

#88 Payment prompt
  src/APICalls.js
  src/components/PurchaseModal/PurchaseModal.css
  src/components/PurchaseModal/PurchaseModal.js
  src/components/RecipePage/RecipePage.js
  src/index.css
Labels: MVP ✅, priority 1 🚨

#93 Display Recipe Rating
  src/APICalls.js
  src/components/MainPage/MainPage.js
  src/components/RecipeCard/RecipeCard.js
Labels: MVP ✅, enhancement ✨

#105 Form fixes
  src/APICalls.js
  src/components/RecipeCard/RecipeCard.js
  src/components/RecipeForm/RecipeForm.js
  src/components/SignUp/SignUpPage.js
Labels: MVP ✅, bug fix 🐛, priority 1 🚨

#108 Stripe Implementation
  .eslintcache
  package-lock.json
  package.json
  public/index.html
  src/components/CheckoutForm/Checkout.js
  src/components/CheckoutForm/CheckoutForm.css
  src/components/CheckoutForm/CheckoutForm.js
  src/components/RecipePage/RecipePage.js
Labels: enhancement ✨
